### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by akshitababel** [ipfs/go-ipfs-api#125]
When I am running a program which is for a web response I am getting a run time error as follows :

http: panic serving 127.0.0.1:43802: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc4200a4a00)
/usr/lib/go-1.10/src/net/http/server.go:1726 +0x11b
panic(0x9b5360, 0xd99230)
/usr/lib/go-1.10/src/runtime/panic.go:502 +0x24a
github.com/ipfs/go-ipfs-api.(*RequestBuilder).Send(0xc4201740a0, 0xb95c60, 0xc420022100, 0x0, 0x0, 0x0)
The code is as follows :
func main() {
	router := httprouter.New()
	router.RedirectTrailingSlash = true
	c := cors.New(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowedMethods:   []string{"GET", "POST", "OPTIONS", "Authorization"},
		AllowedHeaders:   []string{"*"},
		AllowCredentials: true,
	})
	router.GET("/create", StoreAndGetHash)
	router.GET("/read/:hashvalue", GetFile)
	router.GET("/appdata/:appID", ReadPeer)
	router.GET("/update", UpdateAndGetHash)
	router.GET("/createdir", GetDir)
	router.GET("/newkey", GetNewKey)

	log.Fatal(http.ListenAndServe(":3000", c.Handler(router)))
}

func StoreAndGetHash(w http.ResponseWriter, r *http.Request, p httprouter.Params) {
	var read io.Reader
	Shell := shell.NewLocalShell()
	path := r.URL.Query().Get("path")
	typedata := r.URL.Query().Get("mime")
	data := r.URL.Query().Get("content")
	if typedata != "" && data != "" {
		data = strings.Replace(data, " ", "+", -1)
		content := typedata + ";" + data
		file := []byte(content)
		read = bytes.NewReader(file)
	} else if path != "" {
		file, _ := os.Open(path)
		read = io.Reader(file)
	}
	hash, err := Shell.Add(read)
	if err != nil {
		util.WebResponse(w, r, http.StatusNotFound, "")
		return
	}
	util.WebResponse(w, r, http.StatusOK, hash)
	return

}

**Comment by akshitababel** [comment]
I solved the above issue by reinstalling go-ipfs. After re-installing the go-ipfs the program worked perfectly.
